<?php
/**
 * @file
 * 
 * Modules that creats a contact form.  
 */
 
 
 
/**
 * Implements hook_menu
 */
	
function lindsey_contact_form_menu() {
  $items['contact-me'] = array(
    'title' => 'Contact Me',		
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lindsey_contact_form_form'),
    'access arguments' => array('access content'),
    );
  return $items; 
}

/***
 *Implements hook_form
 */
function lindsey_contact_form_form($node, &$form_state) {	
  global $user;	
  $form = array();	
  $form['input_name'] = array(
    '#type' => 'textfield',
    '#title' => t('Name'),	
    '#maxlength' => 128,
    '#required' => TRUE,
  ); 
  $form['input_email'] = array(
    '#type' => 'textfield',
    '#title' => t('Email'),
    '#required' => TRUE,
    '#element_validate' => array('lindsey_form_email_validate'),
    );
    if(!user_is_anonymous()) {
      $form['input_email']['#default_value'] = $user->mail;
    }
  $form['input_select_reason'] = array(
    '#type' => 'select',
    '#title' => 'Reason for Contact',
    '#options' => array(
      0 => 'General Inquires',
      1 => 'Advice',
      2 => 'Freelance Opportunites',
    ),
  );
  $form['input_body'] = array(
    '#type' => 'textarea',
    '#title' => 'Body/Comments',
    '#required' => TRUE,
  );
  $form['contact_form_submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
    '#submit' => array('lindsey_contact_form_form_submit'),
  );
  return $form;
}

//Checks to make sure that the email in the "input_email" field is valid
function lindsey_form_email_validate($form, &$form_state) {
  $value = $form_state['values']['input_email'];
  if (!valid_email_address($value)) {
    form_set_error('input_email',  'Sorry. Your email address is not valid. Please submit a valid E-mail address.');
  }
}


function lindsey_contact_form_form_submit($form, &$form_state) { 
  global $user;	
  $site_email = variable_get('site_mail', '');
  drupal_mail('lindsey_contact_form', 'send_contact_mail', $site_email, language_default(), 
    $params = array(
      'subject' => $form_state['values']['input_select_reason'] . 'from' . $form_state['values']['input_name'],
      'body' => $form_state['values']['input_body'],
    ), $form_state['values']['input_email'], $send = TRUE);	
}



/**
 * Implements hook_mail().
*/
function lindsey_contact_form_mail($key, &$message, $params) {
  switch($key) {
    case 'send_contact_mail':
      $message['subject'] = $params['subject'];
      $message['body'] = $params['body'];
      break;
  }
}
		
